import { daysAgo } from "./format";
import type { Item, Place } from "./types";

export const SEED_PLACES: Place[] = [
  { id: "place-house", name: "House", parentId: null, createdAt: daysAgo(400) },
  { id: "place-garage", name: "Garage", parentId: "place-house", createdAt: daysAgo(400) },
  { id: "place-workbench", name: "Workbench", parentId: "place-garage", createdAt: daysAgo(390) },
  { id: "place-top-drawer", name: "Top drawer", parentId: "place-workbench", createdAt: daysAgo(390) },
  { id: "place-bottom-drawer", name: "Bottom drawer", parentId: "place-workbench", createdAt: daysAgo(390) },
  { id: "place-shelf-2", name: "Shelf 2", parentId: "place-workbench", createdAt: daysAgo(380) },
  { id: "place-blue-toolbox", name: "Blue toolbox", parentId: "place-garage", createdAt: daysAgo(360) },
  { id: "place-cabinet", name: "Cabinet", parentId: "place-garage", createdAt: daysAgo(360) },
  { id: "place-tackle", name: "Tackle box", parentId: "place-garage", createdAt: daysAgo(300) },
  { id: "place-husky", name: "Red Husky toolbox", parentId: "place-garage", createdAt: daysAgo(320) },
  { id: "place-husky-2", name: "Second drawer", parentId: "place-husky", createdAt: daysAgo(320) },
  { id: "place-attic", name: "Attic", parentId: "place-house", createdAt: daysAgo(400) },
  { id: "place-attic-box", name: "Second box on the left", parentId: "place-attic", createdAt: daysAgo(280) },
  { id: "place-office", name: "Office", parentId: "place-house", createdAt: daysAgo(400) },
  { id: "place-desk-drawer", name: "Desk drawer", parentId: "place-office", createdAt: daysAgo(200) },
  { id: "place-bedroom", name: "Bedroom", parentId: "place-house", createdAt: daysAgo(400) },
  { id: "place-nightstand", name: "Nightstand", parentId: "place-bedroom", createdAt: daysAgo(180) },
  { id: "place-basement", name: "Basement", parentId: "place-house", createdAt: daysAgo(400) },
  { id: "place-storage", name: "Storage room", parentId: "place-basement", createdAt: daysAgo(350) },
  { id: "place-shelf-4", name: "Shelf 4", parentId: "place-storage", createdAt: daysAgo(350) },
  { id: "place-vehicle", name: "Vehicle", parentId: null, createdAt: daysAgo(200) },
  { id: "place-mazda", name: "2022 Mazda CX-9", parentId: "place-vehicle", createdAt: daysAgo(200) },
  { id: "place-cargo", name: "Rear cargo area", parentId: "place-mazda", createdAt: daysAgo(200) },
  { id: "place-cargo-bin", name: "Storage compartment", parentId: "place-cargo", createdAt: daysAgo(200) },
];

export const SEED_ITEMS: Item[] = [
  {
    id: "seed-hdmi",
    name: "Spare HDMI cables",
    notes: "Two 6-foot cables and one short adapter cable.",
    category: "cables",
    placeId: "place-blue-toolbox",
    locationPath: ["House", "Garage", "Blue toolbox"],
    photo: "/seed/hdmi-toolbox.jpg",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    id: "seed-drill-bits",
    name: "Extra drill bits",
    notes: "Look for the small black case on the right side of the drawer.",
    category: "tools",
    placeId: "place-top-drawer",
    locationPath: ["House", "Garage", "Workbench", "Top drawer"],
    photo: "/seed/drill-bits.jpg",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(90),
  },
  {
    id: "seed-drill",
    name: "Cordless drill",
    notes: "Battery is usually on the charger on the same shelf.",
    category: "tools",
    placeId: "place-shelf-2",
    locationPath: ["House", "Garage", "Workbench", "Shelf 2"],
    photo: "/seed/cordless-drill.jpg",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(40),
  },
  {
    id: "seed-connectors",
    name: "Electrical connectors",
    notes: "Bag of wire nuts and spade connectors in the second drawer.",
    category: "hardware",
    placeId: "place-husky-2",
    locationPath: ["House", "Garage", "Red Husky toolbox", "Second drawer"],
    photo: "/seed/electrical-connectors.jpg",
    createdAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    id: "seed-lights",
    name: "Christmas lights",
    notes: "Warm-white strings. Second box on the left as you face the attic stairs.",
    category: "seasonal",
    placeId: "place-attic-box",
    locationPath: ["House", "Attic", "Second box on the left"],
    photo: "/seed/christmas-lights.jpg",
    createdAt: daysAgo(280),
    updatedAt: daysAgo(280),
  },
  {
    id: "seed-usbc-office",
    name: "USB-C cable",
    notes: "The longer braided one.",
    category: "cables",
    placeId: "place-desk-drawer",
    locationPath: ["House", "Office", "Desk drawer"],
    photo: "/seed/usbc-cables.jpg",
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
  },
  {
    id: "seed-usbc-nightstand",
    name: "USB-C cable",
    notes: "Short overnight charging cable.",
    category: "cables",
    placeId: "place-nightstand",
    locationPath: ["House", "Bedroom", "Nightstand"],
    photo: null,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  {
    id: "seed-usbc-garage",
    name: "USB-C cable",
    notes: "Spare in the electronics bin mixed with old chargers.",
    category: "cables",
    placeId: "place-cabinet",
    locationPath: ["House", "Garage", "Cabinet"],
    photo: null,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(60),
  },
  {
    id: "seed-air-filters",
    name: "Spare Mazda air filters",
    notes: "Cabin and engine filters, still in the boxes.",
    category: "automotive",
    placeId: "place-cabinet",
    locationPath: ["House", "Garage", "Cabinet"],
    photo: null,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(70),
  },
  {
    id: "seed-hooks",
    name: "Extra fishing hooks",
    notes: "Size 4 and 6 in the top tray of the tackle box.",
    category: "fishing",
    placeId: "place-tackle",
    locationPath: ["House", "Garage", "Tackle box"],
    photo: null,
    createdAt: daysAgo(110),
    updatedAt: daysAgo(110),
  },
  {
    id: "seed-batteries",
    name: "AA batteries",
    notes: "Half-used pack. Also a few AAA mixed in.",
    category: "electronics",
    placeId: "place-desk-drawer",
    locationPath: ["House", "Office", "Desk drawer"],
    photo: null,
    createdAt: daysAgo(16),
    updatedAt: daysAgo(16),
  },
  {
    id: "seed-furnace",
    name: "Extra furnace filters",
    notes: "16x25x1. Two left.",
    category: "household",
    placeId: "place-shelf-4",
    locationPath: ["House", "Basement", "Storage room", "Shelf 4"],
    photo: null,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(45),
  },
  {
    id: "seed-jumper",
    name: "Jumper cables",
    notes: "Rolled up in the cargo compartment under the floor.",
    category: "automotive",
    placeId: "place-cargo-bin",
    locationPath: ["Vehicle", "2022 Mazda CX-9", "Rear cargo area", "Storage compartment"],
    photo: null,
    createdAt: daysAgo(95),
    updatedAt: daysAgo(95),
  },
];
