/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as ItemsItemIdRouteImport } from './routes/items.$itemId'
import { Route as ItemsItemIdEditRouteImport } from './routes/items.$itemId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdEditRoute = ItemsItemIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ItemsItemIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/places': typeof PlacesRoute
  '/items/$itemId': typeof ItemsItemIdRouteWithChildren
  '/items/$itemId/edit': typeof ItemsItemIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/places': typeof PlacesRoute
  '/items/$itemId': typeof ItemsItemIdRouteWithChildren
  '/items/$itemId/edit': typeof ItemsItemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/places': typeof PlacesRoute
  '/items/$itemId': typeof ItemsItemIdRouteWithChildren
  '/items/$itemId/edit': typeof ItemsItemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/places' | '/items/$itemId' | '/items/$itemId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/places' | '/items/$itemId' | '/items/$itemId/edit'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/places'
    | '/items/$itemId'
    | '/items/$itemId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  PlacesRoute: typeof PlacesRoute
  ItemsItemIdRoute: typeof ItemsItemIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId/edit': {
      id: '/items/$itemId/edit'
      path: '/edit'
      fullPath: '/items/$itemId/edit'
      preLoaderRoute: typeof ItemsItemIdEditRouteImport
      parentRoute: typeof ItemsItemIdRoute
    }
  }
}

interface ItemsItemIdRouteChildren {
  ItemsItemIdEditRoute: typeof ItemsItemIdEditRoute
}

const ItemsItemIdRouteChildren: ItemsItemIdRouteChildren = {
  ItemsItemIdEditRoute: ItemsItemIdEditRoute,
}

const ItemsItemIdRouteWithChildren = ItemsItemIdRoute._addFileChildren(
  ItemsItemIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  PlacesRoute: PlacesRoute,
  ItemsItemIdRoute: ItemsItemIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
